build-job:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker build ./build/php -t my-php-image

test-job1:
  stage: test
  script:
    - echo "This job tests something"