variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

build-job:
  stage: build
  image: docker:20.10.16
  services:
  - "docker:dind"
  script:
    - docker build ./build/php -t my-php-image
    - docker build ./build/nginx -t my-nginx-image