variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
build-job:
  stage: build
  services:
  - "docker:dind"
  script:
    - docker build ./build/php -t my-php-image
    - docker build ./build/nginx -t my-nginx-image