build-job:
  stage: build
  services:
  - "docker:dind"
  variables:  # not strictly needed, depending on runner configuration
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  image: docker:stable
  script:
    - docker build ./build/php -t my-php-image
    - docker build ./build/nginx -t my-nginx-image