build-job:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker build -t $IMAGE_TAG ./build/nginx



test-job1:
  stage: test
  script:
    - echo "This job tests something"